### ISSUE TITLE
Toolchain compatibility in documentation

### ISSUE THREAD

**Issue by hilt0n** [atmelcorp/atmel-software-package#100]
Hi there,

Could be good (and nice) to improve the documentation and add the compatible toolchain version to build something usable on the target. Especially for the Sam-Ba applets (no issue available in the Sam-Ba repo so I put that here).

I tried to build working applet (just an update of the existing ones) and lost a lot of time trying the various toolchains available.

From the location given in the Sam-Ba README to get the right toolchain (https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads), I tested the following:

- **gcc-arm-none-eabi-9-2020-q2-update**
Doesn't work, build the binary but Sam-Ba hangs on execution
- **gcc-arm-none-eabi-9-2019-q4-major**
Doesn't work, doesn't build at all cause of floating point handling
- **gcc-arm-none-eabi-8-2019-q3-update**
Doesn't work, doesn't build at all cause of floating point handling
- **gcc-arm-none-eabi-8-2018-q4-major**
Works, finally found the information in the issue #90

**Comment by TonyHan11** [comment]
Thank you very much for your report, The toolchain documentation is improved by adding a suggested version and providing some tips to solve the compatibility issues of different toolchain versions.
