### ISSUE TITLE
Project history and comparison to ASF3/4, MPLAB Harmony, and other alternatives?

### ISSUE THREAD

**Issue by mgazic** [atmelcorp/atmel-software-package#107]
I'm looking for a software library for hardware peripherals on a SAMV71.  In the past I've used ASF3, and purposefully avoided ASF4, Atmel START, and MPLAB Harmony because I want a simple library of source code without any sort of GUI configurator or IDE (especially if it's windows-only), that I can easily integrate into my own codebase and Makefile-based build system.  Who can I talk to about the history of this project, how it compares to alternatives, and your plan for it in the future?  Alternatively, if someone would like to summarize and add the info to the README or somewhere on the Wiki, I think it'd help attract users who are a good fit and dissuade those who are not.  Right now it's unclear if this package is being maintained just to support legacy codebases, or if you think it's a better alternative to what Microchip is currently offering (and if so, why).

Thanks!

**Comment by TonyHan11** [comment]
In addition to this repository, you can also try to find the library for SAMV71 peripherals at https://github.com/atmelcorp/atmel-software-package-samv7. For any further questions please contact Microchip's local sales and use design support channels. 

Thanks.
