### ISSUE TITLE
Wrong IRAM_SIZE information

### ISSUE THREAD

**Issue by rseiti** [atmelcorp/atmel-software-package#108]
Hi,

We found an error on SAM9X60.h definition on software package.

The Internal SRAM0 has 64KBytes (0x10000), but on  https://github.com/atmelcorp/atmel-software-package/blob/master/target/sam9x60/sam9x60.h header , line 493 it is described as 0x20000. 

Could you confirm that it is a lib error?

Thanks,
RIcardo Seiti

**Comment by TonyHan11** [comment]
Thank you for your report. It is a lib error, the size of SRAM0 is 64K and here the definition should be 0x10000.
Fixed in [commit 071dcde089a5e3cb](https://github.com/atmelcorp/atmel-software-package/commit/071dcde089a5e3cb39e5e340f1ce595517a14112)
