### ISSUE TITLE
ADC driver reading from write-only registers

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#11]
drivers/peripherals/adc.c-adc_enable_it() does a read/modify/write operation on the ADC_IER register.  The ADC_IER register is defined as WRITE-ONLY in the SAMA5D2/A5D3/A5D4 datasheets.  
adc_enable_it() should only be writing the mask value to the register, not ORing the mask with the "current contents".

The adc_disable_it() function should also only be writing the mask value to the ADC_IDR register.

**Comment by lfazio** [comment]
Confirmed.

Fixed in the next release.

Found the same pattern in drivers/peripherals/pdmic.c for PDMIC_IER and PDMIC_IDR. Fixed also in next release.
