### ISSUE TITLE
LCD Display pin definition missing pin PC10

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#14]
For 18BPP mode:

The file target/sama5d2/chip_pins.c contains:
/* LCD 18 bits */
#define PINS_LCD_IOS2 {\
	{ PIO_GROUP_C, 0xFFFFF800, PIO_PERIPH_A, PIO_DEFAULT },\
	{ PIO_GROUP_D, 0x00000003, PIO_PERIPH_A, PIO_DEFAULT },\
}

This is missing the definition for pin PC10 that is part of the display bus.

The corrected line should be:
	{ PIO_GROUP_C, 0xFFFFFC00, PIO_PERIPH_A, PIO_DEFAULT },\

**Comment by lfazio** [comment]
Fix in commit 9586283

@dandersonee Feel free to propose pull request so you we can include your contribution more or less directly.
