### ISSUE TITLE
Support for ATWILC1000-SD wifi

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#19]
Any plans near term on the development roadmap to port the WILC drivers to the atmel software package for SAMA5D2?
Updating lib/lwip from lwip1.3.2 to lwip1.4.1?

**Comment by lfazio** [comment]
Concerning the WILC driver, I do not think a bare metal driver already exists and at the moment, we do not have any time to develop it ourselves.

Concerning lwip, we will estimate the workload to update it.

If you want to contribute on any points, feel free to submit a PR...

**Comment by lfazio** [comment]
Concerning lwip, we may consider this in a next sprint.
