### ISSUE TITLE
lcdc_set_color_lut() cannot setup full CLUT.

### ISSUE THREAD

**Issue by ivvd** [atmelcorp/atmel-software-package#23]
`lcdc_set_color_lut()` from `drivers/peripherals/lcdc.c` has `num_colors` parameter which type is `uint8_t` and this loop

```
for (i = 0; i < num_colors; i++)
    layer->reg_clut[i] = clut[i];
```

So  `num_colors` can't be more than 255 and we can't write to last 255th CLUT register. The condition in this loop should be `i <= num_colors`.

**Comment by loiclefort** [comment]
Fixed in commit 81be9fc9d66b302efee3205e1e288b9b4be2bdc4 by removing the <code>num_colors</code> argument. Function <code>lcdc_set_color_lut</code> now always set the full LUT.
