### ISSUE TITLE
CONFIG_PACKAGE for SAMA5D26 typo

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#27]
typo in master/scripts/Makefile.vars.sama5d2 line 158
ifeq ($(CONFIG_CHIP_SAMA5D27),y)
should be:
ifeq ($(CONFIG_CHIP_SAMA5D26),y)

**Comment by loiclefort** [comment]
Yes, of course.
Fixed in commit eb674146335f9bec4bfcf29c9fe2a5abc2918dcf, thanks!
