### ISSUE TITLE
typo in lwipopts.h

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#28]
Typo in /lib/lwip/softpack/include/arch/lwipopts.h (s should be capitalized)
Line 1 is:
#if !defined LWIPOPTs_H
Should be:
#if !defined LWIPOPTS_H

**Comment by lfazio** [comment]
Thank you.

Fixed in bc8709b7e61598e3f21cd7e25ddb48db8179e510.
