### ISSUE TITLE
mmu_disable() function does not work

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#29]
mmu_disable() calls dcache_clean() but that function has an error because

arch/arm/l1cache_cp15.c-dcache_clean() calls 
cp15_dcache_invalidate_setway instead of 
cp15_dcache_clean_setway

looks like a cut/paste error

**Comment by loiclefort** [comment]
Yes it's a cut/paste error, sorry about that.
Fixed in commit 7be965e74e4e47b705faa50caa80c6568aa975e8, thanks.
