### ISSUE TITLE
LWIP compilation issues

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#30]
In file lib/lwip/softpack/netif/ethif.c
Missing:
#include "lwip/dhcp.h"
(needed for DHCP_COARSE_TIMER_SECS )

Missing #if LWIP_TCP around line 92 and 93:
	{ 0, TCP_FAST_INTERVAL,     tcp_fasttmr},
	{ 0, TCP_SLOW_INTERVAL,     tcp_slowtmr},

**Comment by lfazio** [comment]
Fixed in 3751ff20626c853ec0d0b1b5197ab53150f43f0d.

Thank you for your contributions.
