### ISSUE TITLE
Typo in act8945a driver accesses wrong register

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#32]
act8945a.c-act8945a_enable_regulator():
		union _ctrl1 ctrl1;
		uint32_t iaddr = _iaddr_reg[reg - 1] + 1;
should be:
		union _ctrl1 ctrl1;
		uint32_t iaddr = _iaddr_reg[reg - 1] + 2;

**Comment by lfazio** [comment]
Thank for the fix.

Fixed in 29c3d3c536e3217d80bbd9f95b09c87d9144f468.
