### ISSUE TITLE
Incorrect bitmask used for rtc_enable_it()/rtc_disable_it()

### ISSUE THREAD

**Issue by lightagain** [atmelcorp/atmel-software-package#35]
Currently rtc_enable_it()/rtc_disable_it() uses bitmask 0x1F to validate input parameter. This is valid for SAMA5D3 but SAMA5D2 and SAMA5D4 have additional TDERR bit. For these SOC's mask should be 0x3F.

**Comment by lfazio** [comment]
Thank you for the review.

Fixed in a70e989f.
