### ISSUE TITLE
low_power_mode example assert failure

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#36]
Built and ran on SAMA5D2-XULT
failure message:
drivers\i2c\twid.c:782 desc->dma.tx.channel -- assertion failed

Problem caused by examples/low_power_mode/main.c-board_init() missing call to dma_initialize(false) before calls board_cfg_twi_bus()

**Comment by lfazio** [comment]
Fix in commit 77fb8ca7.

Thank you for the report
