### ISSUE TITLE
Low_power_mode example freezes during menu option Init DDR

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#37]
Built and ran on SAMA5D2-XULT
Main calls board_save_misc_power() which turns off all peripheral clocks except PIOA (including TC1 which is needed for usleep used by DDR Init routine)
Possible solution:
In examples/low_power_mode/main.c-menu_init_ddr(), call 
	uint32_t tc_id = get_tc_id_from_addr(BOARD_TIMER_TC, BOARD_TIMER_CHANNEL);
pmc_enable_peripheral(tc_id);
 before call to board_cfg_ddram()
I confirmed this solution works.

or

skip over disabling peripheral id for BOARD_TIMER_TC in board_support.c-board_save_misc_power()
this may be more universal to avoid problems in other drivers using usleep

**Comment by lfazio** [comment]
Fixed in commit bfb0e3fdf8c9754d04a75459f7f182ed9554e515.

Thank you for the bug report.
