### ISSUE TITLE
Incorrect twid driver recover after NACK/timeout (I2C Master mode)

### ISSUE THREAD

**Issue by lightagain** [atmelcorp/atmel-software-package#40]
In case of any error (NACK or timeout) functions _check_nack(), _check_rx_timeout(), _check_tx_timeout(), _twid_wait_twi_transfer() will call twid_configure() which is (by behavior) not recover procedure. twid_configure() will initialize peripheral and allocate DMA channels, which already allocated (resource leak).

There is need in graceful recover procedure of I2C peripheral instead of call to twid_configure().

As I understand we need to analyze TWIHS_SR, than flush fifo's (if we are in FIFO mode),
recover DMA channels (if we are in DMA mode), than issue TWI_CR_LOCKCLR, maybe TWI_CR_CLEAR...
can't find in Datasheet the full recover sequence needed for I2C master...

**Comment by Ian2015** [comment]
Hi lightagain ,
Thanks a lot for your info.
We have fixed it in v2.12 by commit 2906254.
Move the dma channel allocate from twid_configure to twid dma read and write.
In this, twi can change from asyc/polling mode configurated in board init to dma mode,
also avoid source leak while recovery from timeout/nack error.
