### ISSUE TITLE
SAM9x35 - flashing problem with sam-ba

### ISSUE THREAD

**Issue by cedricmarin** [atmelcorp/atmel-software-package#43]
To whom it may concern,

Here in our company, we would like to use sam-ba 3.1.4 to flash the module we are used to work with (AT91sam9x35-CM), as we are experiencing some issues with sam-ba 2.15. Most of the times, we have to repeat (sometimes up to 10 times) the flashing process from the beginning, as it randomly fails during the writing of the rootfs (~120 Mbytes).

Using sam-ba 3.1.4, the flashing process goes fine but the system does not boot. If we try to read the NAND Flash (after flashing the bootstrap), we get the following message:
Error: Command 'verifyboot:at91sam9x5ek-nandflashboot-uboot-3.7.bin': Failed to read pages at address 0x00000000 (status: 3)

We investigated the source codes of **sam-ba** and **atmel-software-package** on GitHub, and found that the PMECC_CLK register is not initialized to a value of 2 in the **pmecc_reset** function in **atmel-software-package/drivers/nvm/nand/pmecc.c** as it should be. In sam-ba 2.x, this register was initialized in the **PMECC_Configure** function in **sam-ba_cdc_linux/applets/sam9x5/libraries/libpmecc/source/pmecc.c**.

We studied the datasheets of SAM9X25, SAM9X35, SAM9X15, SAM9G25, SAM9X35 and the PMECC_CLK register exists for these processors (and appears in the **Pmecc** structure in **atmel-software-package/target/sam9xx5/component/component_pmecc.h**). If we are not mistaken, it should be set to 2. We also noticed that this register does no longer exist for SAMX45 and SAMA processors. It is replaced with a field marked as reserved in the **Pmecc** structure in **atmel-software-package/target/sama5d2/component/component_pmecc.h** for example. So, for new processors, the register configuration is not required.

To resolve this issue, a solution could be to add the following code in the **pmecc_reset** function (in the **atmel-software-package/drivers/nvm/nand/pmecc.c** file).

<code>
#if TARGET_SAM9XX5
PMECC->PMECC_CLK = 2;
#endif
</code>

However, as drivers should be "target-independent", this solution is not very clean...
Could you please tell us what do you think about this ?

We also have an other question : this kind of error seems to indicate that it is no more possible to flash a SAM9XX5 (except perhaps SAM9X45) processor with sam-ba 3.x. Do you know if the flashing process of this (old) processor family has been successfully tested ? Or, if we have to take special care using sam-ba 3.x with this family ?

Thank you in advance for your response,

Best regards.

Cedric Marin

**Comment by loiclefort** [comment]
Hi Cedric,

Thanks for the very detailed bug report.
The sam9xx5 devices (sam9g15, sam9g25, sam9g35, sam9x25 and sam9x35) are supposed to be fully supported on SAM-BA 3. The only difference between this family and the other supported families (sama5d2/3/4 and samv71) is that the sam9xx5 needs DDRAM to load some bigger applets, so the lowlevel and extram applets must be initialized before the NAND/SPI/SDMMC ones.

I have just re-tested with a sam9x35-cm (using SAM-BA 3.2.0-rc3, based on current softpack master) and I did not observe any issue. However, we should probably set the PMECC_CLK register on SAM9xx5 devices as you proposed. We are waiting on a confirmation from our design team.

When you get the "Failed to read pages" message on the host, do you have anything printed on the device console ?

**Comment by cedricmarin** [comment]
Hi Loic,

Thanks for your response ! :)

1- Here, you will find the applet error get from the console:
Applet 'NAND Flash' from softpack 2.5 (v2.5).
Initializing NAND ioSet1 Bus Width 8
ONFI manufacturerId 2c
ONFI onfiPageSize 800
ONFI onfiSpareSize 40
ONFI onfiPagesPerBlock 40
ONFI onfiEccCorrectability 4
PMECC configuration: 0xc0902405
PMECC enabled
Sector size: 512
Sectors per page: 4
Spare size: 64
ECC bits: 4
ECC offset: 36
Buffer Address: 0x2000a540
Buffer Size: 67065856 bytes
NAND applet initialized successfully.
**-E- ecc_read_page_with_pmecc: at B0.P0 Unrecoverable data
Read error at block 0, page 0**

Associated to the sam-ba error:
Opening serial port 'ttyACM0'
Connection opened.
Compatible device detected: SAM9X35.
Detected memory size is 268435456 bytes.
NAND header value 0xc0902405
Executing command 'verifyboot:bootstrap.bin'
Patched file length (13004) at offset 20
Prepended NAND header prefix (0xc0902405)
Added 1124 bytes of padding to align to page size
**Error: Command 'verifyboot:bootstrap.bin': Failed to read pages at address 0x00000000 (status: 3)**

2- We made other tests with several AT91SAM9X35-CM from Embest and noticed that this error does not always occurred... At p349 of SAM9X35's datasheet, it is indicated that PMECC_CLK register is used to adjust the setup time of PMECC module data path. So we think that it is a borderline timing problem. It may happen or not.

3- For now, to resolve the problem, we added this line (before appletInitialize("lowlevel")) in the QML script:
**connection.writeu32(0xFFFFE010, 0x00000002)**
And it works perfectly.

However, we think that it would be better to add this configuration directly in the source code of the applet.

Best regards.

Cedric

**Comment by loiclefort** [comment]
Our design team confirmed that setting PMECC_CLK to 2 is correct for all cases on SAM9xx5.
A fix will be committed soon and the applets will be rebuilt before the final SAM-BA 3.2.0 release.
Thanks!

**Comment by cedricmarin** [comment]
Great !
Thanks !

**Comment by loiclefort** [comment]
Fixed in commit b1a4c40bf9c61e47a4e6bb3a816d89b20e8681e1.
Latest SAM-BA release (3.2.0) includes this fix.
