### ISSUE TITLE
Flashing 8G eMMC fails 

### ISSUE THREAD

**Issue by jlitzinger-kinestral** [atmelcorp/atmel-software-package#46]
The failure occurs due to an integer overflow bug in samba_applets/sdmmc/main.  There is a code path where mem_size in pages is calculated by expanding a value in K to bytes.  This is done with uint32_t types and overflows for parts greater than 4G, resulting in an artificially small image size.  I have a proposed fix that has solved my problem, though it may not be the best long term solution.  Regardless, I will submit a PR for reference.

**Comment by jlitzinger-kinestral** [comment]
PR: https://github.com/atmelcorp/atmel-software-package/pull/47

**Comment by loiclefort** [comment]
PR merged to our internal repo. Fix will be included in next release.

**Comment by loiclefort** [comment]
Fixed in release 2.9
