### ISSUE TITLE
Linker not placing cstartup at beginning of image for the ddram variant

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#5]
Built getting_started for SAMA5D2-XPLAINED using IAR 7.70.1
Recommended change to atmel-software-package/target/sama5d2/toolchain/iar/ddram.icf
Changing: place in DDRAM_region { section .cstartup };
To: place at start of DDRAM_region { section .cstartup };
This enables jumping to the start of the image which is the copy of the vector table so that it then jumps to __iar_program_start.

**Comment by lfazio** [comment]
Your change will be integrated in next release.
