### ISSUE TITLE
Analog header mismatch in drivers folder.

### ISSUE THREAD

**Issue by BlamKiwi** [atmelcorp/atmel-software-package#56]
`drivers/analog/acc.c` and `drivers/analog/adc.c` expect their header files to be in the `peripherals` folder. However the only header files I can find are in the same folder as the source files.  There's either some headers missing or the includes need updating.

**Comment by TonyHan11** [comment]
Unlike other software's architecture there's no dedicate folders for the header files, so the header files are all put in the same folders for the source files currently, thank you for your comment.

**Comment by BlamKiwi** [comment]
That's not the problem. You have missing header files or bad paths. 

For example, in `acc.c` you have the following includes:

    #include "chip.h"
    #include "peripherals/acc.h" 

But there is no such `acc.h` in the `peripherals` folder. Not only that, the `Acc` type is never defined in the `acc.h` that does exist.

**Comment by TonyHan11** [comment]
Yes, the header files's path really needed to be fixed, actually the `Acc` type is defined in `target\samxxxx\component\component_acc.h`.
Similar issues would be fixed in the next release, thank you very much.

**Comment by TonyHan11** [comment]
Fixed in 054f25c
Close the issue.
