### ISSUE TITLE
printf could not run well on floating in software package of SAMA5D2

### ISSUE THREAD

**Issue by barrymchp** [atmelcorp/atmel-software-package#65]
Hi team,
            The customer run our software package on sama5d2, when print floating number, it failed to output. Even if update gcc to newer version-gcc version 4.9.3 20150529 (release) and add --specs=nano.specs -lc -u _printf_float in the linker flags, the issue is not fixed totally, it could output in the first time when call "printf("f1=%f\r\n",f1) and run away in the second time, and even the result is not correct. 
            If printf int or char, it works well. 
            It have been tried to change -mfloat-abi in CFLAG to soft or hard, no improvement.

**Comment by barrymchp** [comment]
![wechat image_20180831132034](https://user-images.githubusercontent.com/40780655/44894264-86afe300-ad21-11e8-94ac-e72216e6aa87.png)

**Comment by TonyHan11** [comment]
Hi barry,

Printing floating number is not supported in softpack by default.

In IAR printf supporting floating number could be enabled well by the following patch:
```
diff --git a/scripts/iar_project.template b/scripts/iar_project.template
index ad2659ac..3f74b377 100644
--- a/scripts/iar_project.template
+++ b/scripts/iar_project.template
@@ -48,11 +48,11 @@
         <option>
           <name>Output variant</name>
           <version>2</version>
-          <state>5</state>
+          <state>0</state>
         </option>
         <option>
           <name>Output description</name>
-          <state>No specifier a, A, no specifier n, no float nor long long.</state>
+          <state>Automatic choice of formatter.</state>
         </option>
         <option>
           <name>GOutputBinary</name>
```

In GNU it's not enough to print floating number by just update "LDFLAGS" as the following:
```
diff --git a/scripts/Makefile.vars b/scripts/Makefile.vars
index 17eb1a8..7bb179f
--- a/scripts/Makefile.vars
+++ b/scripts/Makefile.vars
@@ -124,7 +124,7 @@ CFLAGS_DEFS += -DVARIANT_$(shell echo $(VARIANT) | tr '[:lower:]' '[:upper:]')
 # linker flags
 LDFLAGS = --specs=nano.specs -Wl,--cref -Wl,--check-sections -Wl,--gc-sections
 LDFLAGS += -Wl,--unresolved-symbols=report-all -Wl,--warn-common
-LDFLAGS += -Wl,--sort-section=alignment -lgcc -lc
+LDFLAGS += -Wl,--sort-section=alignment -lgcc -lc -u _printf_float
```
When printing out floating numbers, printf needs more heap space (calling malloc) than it's defined by "HEAP_SIZE" in target/xxx/toolchain/gnu/xxx.ld files. So, **enlarging HEAP_SIZE is needed to solve this issue**. 

Thanks.

**Comment by barrymchp** [comment]
Dear Tony,
         Thx for explanation. I will let the customer follows your comment.

Thanks & Best Regards
Barry xu(徐波)
Senior Embeded Solution Engineer(FAE) (China)
Tel#: 010-85697036
Phone#:13911622820
Address: RM808,Capital group Plaza, No. 6 Chaoyangmen Bei,Beijing, China, 100027
北京市朝阳区朝阳北大街6号首创大厦8层808室

[cid:image001.png@01D4413C.56AB0A00]

发件人: Tony Han <notifications@github.com>
发送时间: 2018年8月31日 14:28
收件人: atmelcorp/atmel-software-package <atmel-software-package@noreply.github.com>
抄送: Barry Xu - A41531 <Bo.Xu@Microchip.com>; State change <state_change@noreply.github.com>
主题: Re: [atmelcorp/atmel-software-package] printf could not run well on floating in software package of SAMA5D2 (#65)


Hi barry,

Printing floating number is not supported in softpack by default.

In IAR printf supporting floating number could be enabled well by the following patch:

diff --git a/scripts/iar_project.template b/scripts/iar_project.template

index ad2659ac..3f74b377 100644

--- a/scripts/iar_project.template

+++ b/scripts/iar_project.template

@@ -48,11 +48,11 @@

         <option>

           <name>Output variant</name>

           <version>2</version>

-          <state>5</state>

+          <state>0</state>

         </option>

         <option>

           <name>Output description</name>

-          <state>No specifier a, A, no specifier n, no float nor long long.</state>

+          <state>Automatic choice of formatter.</state>

         </option>

         <option>

           <name>GOutputBinary</name>

In GNU it's not enough to print floating number by just update "LDFLAGS" as the following:

diff --git a/scripts/Makefile.vars b/scripts/Makefile.vars

index 17eb1a8..7bb179f

--- a/scripts/Makefile.vars

+++ b/scripts/Makefile.vars

@@ -124,7 +124,7 @@ CFLAGS_DEFS += -DVARIANT_$(shell echo $(VARIANT) | tr '[:lower:]' '[:upper:]')

 # linker flags

 LDFLAGS = --specs=nano.specs -Wl,--cref -Wl,--check-sections -Wl,--gc-sections

 LDFLAGS += -Wl,--unresolved-symbols=report-all -Wl,--warn-common

-LDFLAGS += -Wl,--sort-section=alignment -lgcc -lc

+LDFLAGS += -Wl,--sort-section=alignment -lgcc -lc -u _printf_float

When printing out floating numbers, printf needs more heap space (calling malloc) than it's defined by "HEAP_SIZE" in target/xxx/toolchain/gnu/xxx.ld files. So, enlarging HEAP_SIZE is needed to solve this issue.

Thanks.

**Comment by barrymchp** [comment]
Dear Tony,
           Thx for your comment. I would let customer follow your comment and test.

**Comment by barrymchp** [comment]
Dear Tony,
           It works. change in dflag, add -u _printf_float，then changed in file sram.ldand sdram.ld，HEAP_SIZE
 is changed from 0x200 to 0x800.
