### ISSUE TITLE
SAME70 PMC Programmable clock register PCK count

### ISSUE THREAD

**Issue by ot256** [atmelcorp/atmel-software-package#75]
In /target/samv71/component/component_pmc.h

shouldn't it be 
`__IO uint32_t PMC_PCK[8];     /**< \brief (Pmc Offset: 0x0040) Programmable Clock 0 Register */`
?

8 programmable clocks (not 7)

**Comment by TonyHan11** [comment]
Thanks for your report, as there are many configurations for the chip (SAM E70/S70/V70/V71) the available PMC_PCKs are different(due to the clocks for MCAN/TC0).
The patch would be integrated later, thanks.

**Comment by TonyHan11** [comment]
The definition for PCK is updated: https://github.com/atmelcorp/atmel-software-package/commit/215b0738c030fd605792ea6d6a56eb772d5caae8
