### ISSUE TITLE
update lwip to 2.1.2 and make it availlable in atmel studio

### ISSUE THREAD

**Issue by nopeppermint** [atmelcorp/atmel-software-package#79]
Hi
Could you please update lwip to 2.1.2 and make it availlable in atmel studio?
Thanks

**Comment by TonyHan11** [comment]
the lwip has been updated to 2.1.2 in 3fe7d5e and 2e9d269, but there's no plan for softpack to support Atmel Studio untill now.

**Comment by nopeppermint** [comment]
ok, thanks
