### ISSUE TITLE
About HID transfer define

### ISSUE THREAD

**Issue by TATAMA** [atmelcorp/atmel-software-package#83]
in usb/device/hid/hidd_transfer_driver.h
please let HIDDKEYBOARDDRIVER_H to be HIDDTRANSFERDRIVER_H.

I find it will make conflict when you build a USB composite device.

**Comment by TonyHan11** [comment]
Thanks for your report and it has been fixed in [commit dc37955](https://github.com/atmelcorp/atmel-software-package/commit/dc37955abaaa4cea2c348c3f1675cbdd388ea60c)
