### ISSUE TITLE
Error setting AIC Protect mode on SAMA5D2

### ISSUE THREAD

**Issue by dandersonee** [atmelcorp/atmel-software-package#9]
There is a error in the AIC library function.

\drivers\peripherals\aic5.c

Existing code :
```
uint32_t aic_debug_config(Aic * aic, uint8_t protect, uint8_t mask)
{
	uint32_t tmp;

	/* return in case the "Write Protection Mode" is enabled */
	if (aic->AIC_WPMR & AIC_WPMR_WPEN)
		return 1;

	tmp = protect ? (1 << 1) : (0 << 1);
	if (mask)
		tmp++;
	aic->AIC_DCR = tmp;
	return 0;
}
```
According to the SAMA5D2 Datasheet, AIC_DCR bit 1 is GMSK and bit 0 is PROT
This code has the 2 bits swapped.

Updated code : 

```
uint32_t aic_debug_config(Aic * aic, uint8_t protect, uint8_t mask)
{
	uint32_t tmp;

	/* return in case the "Write Protection Mode" is enabled */
	if (aic->AIC_WPMR & AIC_WPMR_WPEN)
		return 1;

	tmp = mask ? (1 << 1) : (0 << 1);
	if (protect)
		tmp++;
	aic->AIC_DCR = tmp;
	return 0;
}
```
Unless the code is right and the datasheet has not been updated.
I have not been able to verify the Protect function by setting either bit.

**Comment by loiclefort** [comment]
Thanks, I have changed the code to use constants from component_aic.h instead:

    dcr = 0;
    if (protect)
            dcr |= AIC_DCR_PROT;
    if (mask)
            dcr |= AIC_DCR_GMSK;
    aic->AIC_DCR = dcr;

Updated code will be in next release.
